platform :ios, '12.0'
inhibit_all_warnings!

target 'Example' do
  use_frameworks!

  pod 'Flags', :path => '../'
  pod 'IGListKit', '4.0.0'
  pod 'SnapKit', '5.0.1'
  pod 'ReactorKit', '3.2.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxOptional', '5.0.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxIGListKit', '2.0.2'
  pod 'HypeUI', '0.1.0'

  target 'ExampleTests' do
    inherit! :complete
    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
  end
end
